### ISSUE TITLE
'dev' tests breaks the first time

### ISSUE THREAD

**Issue by GustJc** [Kuniri/kuniri#145]
The tests breaks on the first clean execution... the second time it executes okay.

To reproduce this.
1. Delete the spec folder
2. Checkout the spec folder (to remove temp files)
3. Rake to run tests.

```
1) Kuniri::Kuniri Verify output integrity Repetition: verify the opening-closing structure
     Failure/Error: @output = File.open("./spec/language/ruby/global_test/repetition/forLoopInClass.xml", "r")
     Errno::ENOENT:
       No such file or directory - ./spec/language/ruby/global_test/repetition/forLoopInClass.xml
     # ./spec/language/ruby/global_test/repetition/complete_class_with_repetition_spec.rb:76:in `initialize'
     # ./spec/language/ruby/global_test/repetition/complete_class_with_repetition_spec.rb:76:in `open'
     # ./spec/language/ruby/global_test/repetition/complete_class_with_repetition_spec.rb:76:in `block (3 levels) in <top (required)>'
```

4 . Run Rake tests again.
The next time the tests run fine. The tests create 4 files that makes them passable the next execution.

```
# On branch dev
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#   spec/language/ruby/global_test/repetition/forLoopInClass.xml
#   spec/language/ruby/global_test/repetition/untilInClass.xml
#   spec/language/ruby/global_test/repetition/whileLoopInClass.xml
#   spec/language/ruby/global_test/simpleFullCode.xml

```

**Comment by rodrigosiqueira** [comment]
@GustJc can you focus on this issue?
