### ISSUE TITLE
Enhancement of 'global_test' structure

### ISSUE THREAD

**Issue by rodrigosiqueira** [Kuniri/kuniri#232]
Tests inside 'spec/language/ruby/global_test/' are important, because they test the final result produced by Kuniri. However, the tests inside this directory have three main problems:
1. When some test fails, it does not show the specific line problem because I used a 'common' function.
2. The test is not smart, because I read all the file many times.
3. Additionally, the name 'gloal_test' is meaningless. 

Refactory this test to fix the three bullets aforementioned. Of course, make this kind of test clever. Consider to move it to another level.

**Comment by giulianobelinassi** [comment]
The point 1, as you can see below, is working as expected:
```
$ rake test:all

  1) Simple blocks as a script Test simple block Global Function: Find times as an expression
     Failure/Error: expect(mixElement).not_to be_nil
     
       expected: not nil
            got: nil
     Shared Example Group: "Block verification" called from ./spec/language/ruby/global_test/blocks/simple_blocks_spec.rb:33
     # ./spec/language/ruby/global_test/blocks/simple_blocks_spec.rb:24:in `block (3 levels) in <top (required)>'

  2) Simple blocks as a script Test simple block Global Function: Find each as an expression
     Failure/Error: expect(mixElement).not_to be_nil
     
       expected: not nil
            got: nil
     Shared Example Group: "Block verification" called from ./spec/language/ruby/global_test/blocks/simple_blocks_spec.rb:37
     # ./spec/language/ruby/global_test/blocks/simple_blocks_spec.rb:24:in `block (3 levels) in <top (required)>'

  3) Simple blocks as a script Test simple block Global Function: Find conditional inside block
     Failure/Error: expect(mixElement).not_to be_nil
     
       expected: not nil
            got: nil
     Shared Example Group: "Block verification" called from ./spec/language/ruby/global_test/blocks/simple_blocks_spec.rb:41
     # ./spec/language/ruby/global_test/blocks/simple_blocks_spec.rb:24:in `block (3 levels) in <top (required)>'
```
