### ISSUE TITLE
Fix all tests (make a passing build)

### ISSUE THREAD

**Issue by GustJc** [Kuniri/kuniri#9]
There are currently several configuration tests falling.

```
3) Kuniri::Kuniri#read_configuration_file Syntax error: wrong extract
     Failure/Error: Error::Configuration_file_error)
     NameError:
       uninitialized constant Error::Configuration_file_error
     # ./spec/core/kuniri_spec.rb:57:in `block (3 levels) in <top (required)>'

  4) Kuniri::Kuniri#read_configuration_file Syntax error: wrong source directory
     Failure/Error: Error::Configuration_file_error)
     NameError:
       uninitialized constant Error::Configuration_file_error
     # ./spec/core/kuniri_spec.rb:45:in `block (3 levels) in <top (required)>'

  5) Kuniri::Kuniri#read_configuration_file Correct return
     Failure/Error: hash_config = @kuniri.read_configuration_file(".kuniri")
     NameError:
       uninitialized constant Error::Configuration_file_error
     # ./app/core/kuniri.rb:57:in `validate_field'
     # ./app/core/kuniri.rb:30:in `read_configuration_file'
     # ./spec/core/kuniri_spec.rb:62:in `block (3 levels) in <top (required)>'

  6) Kuniri::Kuniri#read_configuration_file Wrong path
     Failure/Error: Error::Configuration_file_error)
     NameError:
       uninitialized constant Error::Configuration_file_error
     # ./spec/core/kuniri_spec.rb:27:in `block (3 levels) in <top (required)>'

  7) Kuniri::Kuniri#read_configuration_file Syntax error: not use ':'
     Failure/Error: Error::Configuration_file_error)
     NameError:
       uninitialized constant Error::Configuration_file_error
     # ./spec/core/kuniri_spec.rb:33:in `block (3 levels) in <top (required)>'

  8) Kuniri::Kuniri#read_configuration_file Syntax error: not valid language
     Failure/Error: Error::Configuration_file_error)
     NameError:
       uninitialized constant Error::Configuration_file_error
     # ./spec/core/kuniri_spec.rb:39:in `block (3 levels) in <top (required)>'

  9) Kuniri::Kuniri#read_configuration_file Syntax error: wrong output directory
     Failure/Error: Error::Configuration_file_error)
     NameError:
       uninitialized constant Error::Configuration_file_error
     # ./spec/core/kuniri_spec.rb:51:in `block (3 levels) in <top (required)>'

  10) Kuniri::Kuniri#read_configuration_file Correct return: Case sensitive language
     Failure/Error: expect(@kuniri.read_configuration_file(".kuniri")).to include(
     NameError:
       uninitialized constant Error::Configuration_file_error
     # ./app/core/kuniri.rb:57:in `validate_field'
     # ./app/core/kuniri.rb:30:in `read_configuration_file'
     # ./spec/core/kuniri_spec.rb:72:in `block (3 levels) in <top (required)>'
```

There are also 2 ruby_syntax tests falling from class_extract and method_extract but they should be automatically correct after the ruby_syntax token's are properly implemented.

```
1) Languages::RubySyntax#class_extract Class name
     Failure/Error: expect(classList.shift).to eq("RubySupportTest")
     NoMethodError:
       undefined method `shift' for #<Languages::ClassData:0x00000001b0b598>
     # ./spec/language/ruby_syntax_spec.rb:80:in `block (3 levels) in <top (required)>'

  2) Languages::RubySyntax#method_extract Method name
     Failure/Error: expect(methodName.shift).to eq("initialize")

       expected: "initialize"
            got: :add_attribute

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -"initialize"
       +:add_attribute

     # ./spec/language/ruby_syntax_spec.rb:93:in `block (3 levels) in <top (required)>'
```

**Comment by rodrigosiqueira** [comment]
I'm working in this issue.

**Comment by GustJc** [comment]
@rodrigosiqueira, when you are working on a issue you can set your username in Assignee on the right.

**Comment by rodrigosiqueira** [comment]
Done
